basePath: /v1
host: 127.0.0.1:8080
info:
  contact: {}
  description: This is PIR5 HealthCheck worker and API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: health-worker
  version: "1.0"
paths: {}
swagger: "2.0"
